name: File Versioning

on:
  push:
  workflow_run:
    workflows: ["GitHub Pages"]
    types:
      - completed

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run the versioning script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUSHED_COMMITS: ${{ toJson(github.event.commits) }}
        run: python .github/scripts/updateversions.py
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add versions.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update file versions"
            git push
          fi
